set(_CATKIN_CURRENT_PACKAGE "towr_ros")
set(towr_ros_VERSION "1.4.1")
set(towr_ros_MAINTAINER "Alexander W. Winkler <alexander.w.winkler@gmail.com>")
set(towr_ros_PACKAGE_FORMAT "2")
set(towr_ros_BUILD_DEPENDS "libncurses-dev" "message_runtime" "message_generation" "std_msgs" "visualization_msgs" "roscpp" "rosbag" "xpp_states" "xpp_msgs" "towr")
set(towr_ros_BUILD_EXPORT_DEPENDS "libncurses-dev" "message_runtime" "message_generation" "std_msgs" "visualization_msgs" "roscpp" "rosbag" "xpp_states" "xpp_msgs" "towr")
set(towr_ros_BUILDTOOL_DEPENDS "catkin")
set(towr_ros_BUILDTOOL_EXPORT_DEPENDS )
set(towr_ros_EXEC_DEPENDS "xterm" "xpp_hyq" "rviz" "rqt_bag" "libncurses-dev" "message_runtime" "message_generation" "std_msgs" "visualization_msgs" "roscpp" "rosbag" "xpp_states" "xpp_msgs" "towr")
set(towr_ros_RUN_DEPENDS "xterm" "xpp_hyq" "rviz" "rqt_bag" "libncurses-dev" "message_runtime" "message_generation" "std_msgs" "visualization_msgs" "roscpp" "rosbag" "xpp_states" "xpp_msgs" "towr")
set(towr_ros_TEST_DEPENDS )
set(towr_ros_DOC_DEPENDS )
set(towr_ros_URL_WEBSITE "http://github.com/ethz-adrl/towr")
set(towr_ros_URL_BUGTRACKER "http://github.com/ethz-adrl/towr/issues")
set(towr_ros_URL_REPOSITORY "")
set(towr_ros_DEPRECATED "")